name: CSharpier Code Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  csharpier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: temporal-examples
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install CSharpier
        run: dotnet tool install --global csharpier

      - name: Run CSharpier check
        run: dotnet csharpier --check .
